name: Deploying vite build output to Netlify
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Build Process
        run: | 
          npm ci
          npm run build
        continue-on-error: false

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploying Site
        run: netlify deploy --prod --dir="$GITHUB_WORKSPACE/dist" --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
