name: Deploying to Netlify

on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to netlify
        uses: South-Paw/action-netlify-cli@v2
        id: netlify
        with:
          args: 'deploy --dir \"./public\" --message \"draft [${{ github.sha }}]\"'
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
