name: pushing using action-netlify-cli from github

on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Setting up public directory
        run: | 
          rm -rf public
          mkdir -p public
          cp -r src/* public/
          ls -la public/

      - name: Publish
        uses: South-Paw/action-netlify-cli@v2
        id: netlify
        with:
          args: 'deploy --dir \"./public\" --message \"draft [${{ github.sha }]}\"'
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
