name: Deploying vite build output to Netlify
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Build Process
        run: | 
          npm ci
          npm run build
        continue-on-error: false

      - name: Deploying Site
        uses: South-Paw/action-netlify-cli@v2
        with:
          publish-dir: dist
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
