name: Deploy to Netlify
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Deployed Site"
      run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
